# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeersList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeersList

  target 'BeersListTests' do
    inherit! :search_paths
    pod 'OHHTTPStubs/Swift'
    # Pods for testing
  end

  target 'BeersListUITests' do
    # Pods for testing
  end

end
